"""Backend half of the frontend/backend save contract.

The JSON files in ``fixtures/frontend_save_payloads/`` are generated by the
frontend test ``frontend/src/lib/services/save-contract.test.ts`` from the real
``buildDataModel`` + real JSON serialization (undefined keys dropped). They are
POSTed here byte-for-byte against a pre-seeded data_model.yml, so both sides are
tested against the same payloads.
"""

import json
import os

import pytest
import yaml

FIXTURE_DIR = os.path.join(
    os.path.dirname(__file__), "fixtures", "frontend_save_payloads"
)


def _load_payload(name: str) -> dict:
    with open(os.path.join(FIXTURE_DIR, f"{name}.json"), "r") as f:
        return json.load(f)


def _seed(path: str, entities: list) -> None:
    with open(path, "w") as f:
        yaml.safe_dump(
            {"version": 0.1, "entities": entities, "relationships": []},
            f,
            sort_keys=False,
        )


def _saved_entity(path: str, entity_id: str) -> dict:
    with open(path, "r") as f:
        saved = yaml.safe_load(f)
    return next(e for e in saved["entities"] if e["id"] == entity_id)


def _seeded_bound_orders() -> dict:
    """On-disk state for the bound entity: reconcile- and backend-owned keys."""
    return {
        "id": "orders",
        "label": "Orders",
        "model_ref": "model.proj.orders",
        "framework_tags": ["nightly"],
        "tags": ["stale_display_tag"],
        "ui_tags": ["old_ui_tag"],
        "description": "Seeded description",
        "domain": "sales",
        "source_system": ["SAP"],
        "roles": [{"label": "Legacy", "role": "legacy", "source": "dbt"}],
    }


def _loaded_entity(test_client, entity_id: str) -> dict:
    response = test_client.get("/api/data-model")
    assert response.status_code == 200
    return next(e for e in response.json()["entities"] if e["id"] == entity_id)


class TestUnboundEntityPayload:
    def test_unbound_payload_round_trips(
        self, test_client, temp_data_model_path
    ):
        _seed(temp_data_model_path, [])
        response = test_client.post(
            "/api/data-model", json=_load_payload("unbound_entity")
        )
        assert response.status_code == 200

        saved = _saved_entity(temp_data_model_path, "customer")
        assert saved["tags"] == ["core", "pii"]
        assert saved["source_system"] == ["SAP"]
        assert saved["entity_type"] == "dimension"
        assert saved["description"] == "A buyer"
        assert saved["roles"] == [
            {"label": "Buyer", "role": "buyer", "source": "user"}
        ]
        assert saved["drafted_fields"] == [
            {
                "name": "customer_id",
                "datatype": "int",
                "description": "Key",
                "origin": [{"system": "SAP"}, {"table": "KNA1"}],
            }
        ]
        # unbound entities never carry bound-only keys
        assert "ui_tags" not in saved
        assert "framework_tags" not in saved
        assert "model_ref" not in saved

        loaded = _loaded_entity(test_client, "customer")
        assert loaded["tags"] == ["core", "pii"]
        assert loaded["roles"] == [
            {"label": "Buyer", "role": "buyer", "source": "user"}
        ]
        assert loaded["drafted_fields"][0]["origin"] == [
            {"system": "SAP"},
            {"table": "KNA1"},
        ]

    def test_unbound_omitted_tags_clear_existing(
        self, test_client, temp_data_model_path
    ):
        """Omitted `tags` on an unbound entity means the user cleared them."""
        _seed(
            temp_data_model_path,
            [{"id": "customer", "label": "Customer", "tags": ["core", "pii"]}],
        )
        payload = _load_payload("unbound_entity")
        del payload["entities"][0]["tags"]

        assert test_client.post("/api/data-model", json=payload).status_code == 200
        assert "tags" not in _saved_entity(temp_data_model_path, "customer")


class TestBoundEntityPayload:
    def test_bound_payload_preserved_and_cleared_keys(
        self, test_client, temp_data_model_path
    ):
        _seed(temp_data_model_path, [_seeded_bound_orders()])
        payload = _load_payload("bound_entity")
        # Sanity: the frontend really omits these keys for a bound entity.
        for omitted in ("tags", "framework_tags", "source_system", "description"):
            assert omitted not in payload["entities"][0]

        response = test_client.post("/api/data-model", json=payload)
        assert response.status_code == 200

        saved = _saved_entity(temp_data_model_path, "orders")
        # preserved although omitted
        assert saved["framework_tags"] == ["nightly"]
        assert saved["model_ref"] == "model.proj.orders"
        # sent by the frontend
        assert saved["ui_tags"] == ["finance"]
        assert saved["entity_type"] == "fact"
        # roles: existing on-disk role kept, incoming merged in
        assert saved["roles"] == [
            {"label": "Legacy", "role": "legacy", "source": "dbt"},
            {"label": "Order", "role": "order", "source": "dbt"},
        ]
        # cleared because omitted / never persisted for bound entities
        assert "tags" not in saved
        assert "source_system" not in saved
        assert "description" not in saved
        assert "domain" not in saved

        loaded = _loaded_entity(test_client, "orders")
        assert loaded["framework_tags"] == ["nightly"]
        assert loaded["ui_tags"] == ["finance"]
        assert loaded["roles"] == [
            {"label": "Legacy", "role": "legacy", "source": "dbt"},
            {"label": "Order", "role": "order", "source": "dbt"},
        ]

    def test_empty_ui_tags_clear_but_framework_tags_survive(
        self, test_client, temp_data_model_path
    ):
        _seed(temp_data_model_path, [_seeded_bound_orders()])
        payload = _load_payload("bound_entity_ui_tags_cleared")
        # Frontend serializes empty ui_tags as an omitted key.
        assert "ui_tags" not in payload["entities"][0]

        assert test_client.post("/api/data-model", json=payload).status_code == 200

        saved = _saved_entity(temp_data_model_path, "orders")
        assert "ui_tags" not in saved
        assert saved["framework_tags"] == ["nightly"]

        loaded = _loaded_entity(test_client, "orders")
        assert loaded.get("ui_tags") in (None, [])
        assert loaded["framework_tags"] == ["nightly"]

    def test_omitted_roles_preserved(self, test_client, temp_data_model_path):
        _seed(temp_data_model_path, [_seeded_bound_orders()])
        payload = _load_payload("bound_entity_roles_omitted")
        assert "roles" not in payload["entities"][0]

        assert test_client.post("/api/data-model", json=payload).status_code == 200

        saved = _saved_entity(temp_data_model_path, "orders")
        assert saved["roles"] == [
            {"label": "Legacy", "role": "legacy", "source": "dbt"}
        ]
        assert saved["framework_tags"] == ["nightly"]
        assert saved["ui_tags"] == ["finance"]
